blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://blaver.dev
    about: Read the documentation for the project.
  - name: Questions & Discussions
    url: https://github.com/luciferreeves/blaver/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
