name: "\U0001F680 Feature Request"
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: It would be better if you just copy from [...] library...
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered 
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I do not need to do this... 
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
      placeholder: Just file it, already...
