name: Build
'on':
  push:
    branches:
      - master
      - dev
      - coverage-test
  pull_request:
    branches:
      - master
      - dev
      - coverage-test
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        node-version:
          - 14.x
    steps:
      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
      - run: npm test

      - name: Run tests
        run: npm run test-cov
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          flag-name: ${{matrix.os}}-node-${{ matrix.node }}
          parallel: true
  finish:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          parallel-finished: true
          
